const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript'),React=require('react'),renderer=require('react-test-renderer');
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
function load(file,overrides){const filename=path.resolve(file),m=new Module(filename,module);m.filename=filename;m.paths=Module._nodeModulePaths(path.dirname(filename));const original=m.require.bind(m);m.require=name=>Object.hasOwn(overrides,name)?overrides[name]:original(name);m._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022}}).outputText,filename);return m.exports;}
const ui=new Proxy({}, {get:(_,name)=>function Control(props){return React.createElement(String(name),props,props.children)}});
let session,exported,removed=[],fail=false;const calls=[];
const capi=async(url,opts={})=>{calls.push(url);if(fail)throw new Error('Offline: please retry');if(url==='/auth/sessions')return {sessions:[{id:'current',current:true,device_name:'Phone',last_seen_at:new Date().toISOString()},{id:'other',device_name:'Browser',last_seen_at:new Date().toISOString()}].filter(x=>!removed.includes(x.id))};if(url.startsWith('/auth/sessions/')){removed.push(url.split('/').pop());return {}};if(url==='/auth/export')return {user:{first_name:'QA'},bookings:[]};if(url.startsWith('/auth/me?')){const page=Number(new URL('http://local'+url).searchParams.get('order_page'));return {orders:[{id:String(page),items:'Page '+page,total_cents:1000,currency:'USD',status:'paid',created_at:new Date().toISOString(),shipments:[{seller:'Studio',status:'shipped',fulfilment:'ship',tracking:'QA-TRACK'}]}],order_page:{pages:3,page}}};throw new Error('unexpected '+url)};
session={clientToken:'QA',businessToken:null,capi,signOut:async()=>{session={...session,clientToken:null}}};
const useSession=()=>session;
const {useLoad}=load('src/lib/use-load.ts',{'./session':{useSession}});
const common={'react-native':ui,'expo-router':{router:{replace:()=>{}}},'@/components/ui':ui,'@/components/cc-ui':ui,'@/lib/session':{useSession},'@/lib/use-load':{useLoad},'@/lib/format':{money:n=>'$'+n/100},'@/lib/cc-data':{openPay:async()=>{},useReturn:()=>{}},'@/lib/mj-files':{shareFile:async x=>{exported=x;return 'saved'}}};
const Privacy=load('src/app/c/account/privacy.tsx',common).default,Orders=load('src/app/c/account/orders.tsx',common).default;
let tree;const settle=()=>new Promise(r=>setImmediate(r));
const mount=async Component=>renderer.act(async()=>{tree=renderer.create(React.createElement(Component));await settle()});
const text=node=>node.children.map(x=>typeof x==='string'?x:typeof x==='number'?String(x):text(x)).join('');
const button=label=>tree.root.findAllByType('Btn').find(x=>text(x)===label);
async function click(label){const b=button(label);assert(b,'missing button '+label);assert(!b.props.disabled,'disabled '+label);await renderer.act(async()=>{b.props.onPress();await settle();await settle()})}
(async()=>{
 await mount(Orders);assert(tree.root.findAllByType('T').some(x=>text(x)==='Page 1'));await click('Next');assert(calls.some(x=>x.includes('order_page=2')));assert(tree.root.findAllByType('T').some(x=>text(x)==='Page 2'));await click('Show awaiting payment');assert(calls.at(-1).includes('order_page=1&status=pending'));
 fail=true;await click('Next');assert(tree.root.findAllByType('Failed').length===1,'failure must be visible');assert(!tree.root.findAllByType('Empty').length,'failure must not look empty');fail=false;await renderer.act(async()=>{tree.root.findByType('Failed').props.onRetry();await settle()});assert(!tree.root.findAllByType('Failed').length);await renderer.act(async()=>tree.unmount());
 await mount(Privacy);assert(button('Permanently delete my account').props.disabled,'delete needs explicit confirmation');await click('Export my data');assert.equal(exported.name,'logaluxe-account.json');assert.equal(JSON.parse(exported.text).user.first_name,'QA');await click('Sign out this device');assert(removed.includes('other'));assert(!button('Sign out this device'),'revoked device removed');await click('Sign out all other devices');assert(removed.includes('others'));await renderer.act(async()=>tree.unmount());
 session={...session,clientToken:null};await mount(Privacy);assert(tree.root.findAllByType('SignInGate').length===1);await renderer.act(async()=>tree.unmount());await mount(Orders);assert(tree.root.findAllByType('SignInGate').length===1);await renderer.act(async()=>tree.unmount());
 console.log('PASS: signed-in mobile orders pagination/filter/failure/retry, privacy export/device revocation, deletion confirmation and guest access gates');
})().catch(e=>{console.error(e);process.exitCode=1});
